#![feature(concat_idents)]
#![feature(proc_macro_hygiene)]
#![allow(unused_imports)]

mod mario;
mod donkey;
mod link;
mod samus;
mod samusd;
mod yoshi;
mod kirby;
mod fox;
mod pikachu;
mod luigi;
mod ness;
mod captain;
mod purin;
mod peach;
mod daisy;
mod koopa;
mod popo_nana;
mod sheik;
mod zelda;
mod mariod;
mod pichu;
mod falco;
mod marth;
mod lucina;
mod younglink;
mod ganon;
mod mewtwo;
mod koopag;
mod roy;
mod chrom;
mod gamewatch;
mod metaknight;
mod pit;
mod pitb;
mod szerosuit;
mod wario;
mod snake;
mod ike;
mod ptrainer;
mod diddy;
mod lucas;
mod sonic;
mod dedede;
mod pikmin;
mod lucario;
mod robot;
mod toonlink;
mod wolf;
mod murabito;
mod rockman;
mod wiifit;
mod rosetta;
mod littlemac;
mod gekkouga;
mod miifighter;
mod miiswordsman;
mod miigunner;
mod palutena;
mod pacman;
mod reflet;
mod shulk;
mod koopajr;
mod duckhunt;
mod ryu;
mod ken;
mod cloud;
mod kamui;
mod bayonetta;
mod inkling;
mod ridley;
mod simon;
mod richter;
mod krool;
mod shizue;
mod gaogaen;
mod pakkun;
mod jack;
mod brave;
mod buddy;
mod dolly;
mod master;
mod tantan;
mod custom;

#[skyline::main(name = "acmd_test")]
pub fn main() {
    mario::install();
    donkey::install();
    link::install();
    samus::install();
    samusd::install();
    yoshi::install();
    kirby::install();
    fox::install();
    pikachu::install();
    luigi::install();
    ness::install();
    captain::install();
    purin::install();
    peach::install();
    daisy::install();
    koopa::install();
    popo_nana::install();
    sheik::install();
    zelda::install();
    mariod::install();
    pichu::install();
    falco::install();
    marth::install();
    lucina::install();
    younglink::install();
    ganon::install();
    mewtwo::install();
    koopag::install();
    roy::install();
    chrom::install();
    gamewatch::install();
    metaknight::install();
    pit::install();
    pitb::install();
    szerosuit::install();
    wario::install();
    snake::install();
    ike::install();
    ptrainer::install();
    diddy::install();
    lucas::install();
    sonic::install();
    dedede::install();
    pikmin::install();
    lucario::install();
    robot::install();
    toonlink::install();
    wolf::install();
    murabito::install();
    rockman::install();
    wiifit::install();
    rosetta::install();
    littlemac::install();
    gekkouga::install();
    miifighter::install();
    miiswordsman::install();
    miigunner::install();
    palutena::install();
    pacman::install();
    reflet::install();
    shulk::install();
    koopajr::install();
    duckhunt::install();
    ryu::install();
    ken::install();
    cloud::install();
    kamui::install();
    bayonetta::install();
    inkling::install();
    ridley::install();
    simon::install();
    richter::install();
    krool::install();
    shizue::install();
    gaogaen::install();
    pakkun::install();
    jack::install();
    brave::install();
    buddy::install();
    dolly::install();
    master::install();
    tantan::install();
    custom::install();
}