name: Rust Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  plugin:
    env:
      PLUGIN_NAME: skyline-rs-template # Replace this with your plugin name!
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:2.1.0
    steps:
    - uses: actions/checkout@v2
    - name: Build release NRO
      run: |
        PATH=$PATH:/root/.cargo/bin /root/.cargo/bin/cargo-skyline skyline build --release
      env:
        HOME: /root
    - name: Upload plugin artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: target/aarch64-skyline-switch/release/lib${{env.PLUGIN_NAME}}.nro
# uncomment the build step below to build on every change to master.
#   upload:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/master'
#     needs:
#       - plugin
#     steps:
#     - name: Download all artifacts
#       uses: actions/download-artifact@v2
#     - name: Update Release
#       uses: meeDamian/github-release@2.0
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#         prerelease: true
#         allow_override: true
#         gzip: false
#         tag: beta
#         name: beta
#         body: >
#           Beta built off of the latest code in the repository. 
#         files: >
#           plugin/*
